### ISSUE TITLE
explore gRPC options - binder

### ISSUE THREAD

**Issue by jldec** [projectriff/java-function-invoker#10]
Once we have some IDL from the sidecar (from @ericbottard), we can begin to explore options of how to take the incoming messages and push them down to spring-cloud-function. Maybe a stream, via the message channels that it exposes. Maybe something else.

**Comment by ericbottard** [comment]
See https://github.com/projectriff/function-proto/pull/6

I can take a look at this if you want @dsyer

**Comment by dsyer** [comment]
Sure. I was waiting to hear about where to get the proto files / generated classes from. It seemed like they were evolving last time I looked.

**Comment by ericbottard** [comment]
Yes, they were. The PR I linked above is what we're aiming for (prior discussion though, as most of us are on holiday). Basically, `byte[]` for payload and `Map<String, String[]>` for headers.

**Comment by ericbottard** [comment]
There are corresponding PRs in the `function-sidecar`, if you want to test in the context of riif: https://github.com/projectriff/function-sidecar/pull/36

**Comment by dsyer** [comment]
See #26

**Comment by trisberg** [comment]
#26 is merged, so closing this issue
