### ISSUE TITLE
Cannot run java functions using Flux

### ISSUE THREAD

**Issue by Turbots** [projectriff/java-function-invoker#100]
Tried to create a Java function using Flux and it threw a `ClassNotFoundException` for `reactor.core.publisher.Flux`

You can find the relevant commit here: https://github.com/Turbots/mandelbrot-calculator/commit/ca1e33c7d5d9345d5e8299145ea58d413985417c

**Comment by trisberg** [comment]
I can reproduce this, so I assume it is related to how we load the function. 

I also tried with a function bean  for `Function<Flux<String>, Flux<String>> uppercase()` that is part of a full Boot app and got another error: "java.lang.String cannot be cast to reactor.core.publisher.Flux" when invoking the riff function. Same function works fine running it as a web app with `java -jar`.

I wonder if @dsyer has some ideas

**Comment by dsyer** [comment]
I can't reproduce it. This works for me (from this project after successful build):

```
$ docker run -p 8080:8080 -v `pwd`/target/it:/it projectriff/java-function-invoker --function.uri=file:///it/pojo/target/dependency?handler=uppercase
$  curl localhost:8080 -d '{"value":"foo"}' -H "Content-Type: application/json"
[{"value":"FOO"}]
```

(Also works with "latest" and "0.1.2" labels on the docker image.)

So I think the problem must be the function. In @Turbots case it is clearly wrong: once you have either input or output of `Flux` then they both have to be (i.e. `Function<Flux,Flux>` would work). We should probably fail in a more intelligible way (happy to make this issue about that if we can agree that it isn't something more serious).

I also added a sample function with `Flux<String>` to the "pojo" sample and that worked as well:

```
$ curl localhost:8080 -d 'foo' -H "Content-Type: text/plain"
["FOO"]
```

So what is @trisberg doing differently?

**Comment by trisberg** [comment]
I built with the new buildpack v3 support. That ends up running a command like `java -jar /workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.2-exec.jar $JAVA_OPTS --function.uri='file:///workspace/app?handler=be.ordina.function.MandelbrotCalculator'` where `/workspace/app` directory only has the app classes and no dependencies. This might be an issue for the buildpack rather than the invoker.

**Comment by dsyer** [comment]
The `MandelbrotCalculator` had an illegal function signature (it has now been updated). I was more interested in your `Flux<String>` example, which I couldn't reproduce. How did you find out about the missing dependencies (I never had that issue either)? The mandelbrot project has 0 runtime dependencies, so I'm not sure it is actually an issue is it?

**Comment by trisberg** [comment]
I just realized we might require a fat-jar or an uber-jar for the user function in the mandelbrot example

**Comment by dsyer** [comment]
> I just realized we might require a fat-jar or an uber-jar for the user function in the mandelbrot example

Not in its current form (it only has lombok as a dependency).

**Comment by trisberg** [comment]
For a plain function I get the classpath issue on startup where it can't find reactor classes

clone https://github.com/trisberg/upper-java-flux

and then run the following from the root of that repo
```
pack build $USER/upper-java-flux --path . --builder nebhale/riff-build
docker run -p 8080:8080 $USER/upper-java-flux
...
Caused by: java.lang.ClassNotFoundException: reactor.core.publisher.Flux
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration$BeanCreatorClassLoader.loadClass(FunctionCreatorConfiguration.java:443)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more
```

**Comment by trisberg** [comment]
For a boot function app I get an exception invoking it. Same app runs fine from `java -jar` but not packaged as a riff function with buildpack.

clone https://github.com/trisberg/upper-boot-flux

and then run the following from the root of that repo
```
pack build $USER/upper-boot-flux --path . --builder nebhale/riff-build
docker run -p 8080:8080 $USER/upper-boot-flux
```

invoking with:
```
curl localhost:8080 -w '\n' -H "Content-Type: text/plain" -d hello 
{"timestamp":"Oct 2, 2018 4:37:22 PM","status":500,"error":"Internal Server Error","message":"java.lang.String cannot be cast to reactor.core.publisher.Flux","path":"/"}
```

**Comment by dsyer** [comment]
The `upper-java-flux` project uses the shade plugin. I don't think we ever supported that (and I don't expect it to work because `Flux` needs to be in a shared class loader). The `upper-boot-flux` looks like it should work and it's pretty much identical to one of our integration tests. I'll have a closer look tomorrow.

**Comment by trisberg** [comment]
With or without the shade plugin, it gets the same ClassNotFoundException, I added the plugin to try to work around it.

**Comment by dsyer** [comment]
This works for me (for both samples if you change the target dir and the handler spec):

```
$ docker run -p 8080:8080 -v ${HOME}/dev/riff/samples/upper-java-flux/target:/target projectriff/java-function-invoker --function.uri=file:/target/upper-java-flux-0.0.1.jar?handler=functions.Upper
```

Running the invoker with `java -jar` doesn't work and seems to fail in a similar way, so we can treat that as an issue if you want (but not very high priority). The riff buildpack looks like it is maybe broken? I don't yet know how to debug that (buildpacks are mysterious to me).

**Comment by trisberg** [comment]
so in the buildpack we have the opposite - the invoker is a downloaded jar file and the function is in an exploded format

**Comment by dsyer** [comment]
Can we fix the buildpack? It's not great to use the jar for cold start times.

**Comment by Turbots** [comment]
Happy to see you have come to the same conclusion as I just did, mainly that this is caused by the Buildpack. I should have mentioned this in my example and could have saved a lot of time. And indeed, my initial implementation was clearly wrong. Let's see if we can fix the buildpack!

**Comment by trisberg** [comment]
I created an issue for the riff-buildpack here: https://github.com/projectriff/riff-buildpack/issues/7
