### ISSUE TITLE
Explore WebFlux instead of s-c-f ArgumentResolver

### ISSUE THREAD

**Issue by ericbottard** [projectriff/java-function-invoker#11]
Spring 5.0 might be able to handle some of the content negotiation and other protocol concerns for the function invoker when it is accepting HTTP inputs (instead of using spring-cloud-function-web, or anything higher level than spring-cloud-function-context). The function signature would still need to be inspected and would not be available at compile time for WebFlux in a `@RequestMapping` (for example), but maybe could be bridged to the existing Spring decoders/encoders.

**Comment by dsyer** [comment]
I'm pretty sure the Spring Boot team recommends *not* trying to run Spring 5.0 with Spring Boot 1.5.x, so this might be a non-starter for that reason (at least until Spring Boot 2.0 starts up a bit faster). Worth a look though, and might make it easier for me to decide whether to go with a Spring Cloud Stream approach to HTTP binding, or stick to a custom HTTP layer in Spring Cloud Function. The only reason I can think of for *not* doing that right now is if there are concerns about startup time (quite possible, given that Spring Cloud Stream requires a bit more juice on startup than a vanilla MVC/Webflux app).

**Comment by dsyer** [comment]
We moved to Spring Cloud Function 2.0 and WebFlux by default now, so this issue is probably obsolete. We use the WebFlux content negotiation as much as possible in Spring Cloud Function.
