### ISSUE TITLE
Support looking up function class using custom entry in MANIFEST

### ISSUE THREAD

**Issue by trisberg** [projectriff/java-function-invoker#110]
We should be able to detect the function class using a custom entry in the MANIFEST (we already detect `Start-Class` in a Spring Boot application).

E.g. we should support `<Function-Class>functions.Upper</Function-Class>`

**Comment by dsyer** [comment]
That's easy (can be added to `spring-cloud-function-deployer` maybe, if not here, since we already do main class detection there). FWIW it should be overridable by the `function.uri`, otherwise a JAR can only ever contain one function.

**Comment by dsyer** [comment]
That should be working now (through snapshots in spring-cloud-function). Will be in RC2 on Monday.
