### ISSUE TITLE
Don't require uber jar

### ISSUE THREAD

**Issue by sbawaska** [projectriff/java-function-invoker#115]
For java function that have compile dependencies, the build needs to be configured to produce a uber (fat) jar. Given that those dependencies were just downloaded while compiling, we should be able to put them on the classpath so that user don't have to go through trouble of creating fat jars.

**Comment by dsyer** [comment]
Why is it "trouble" to create a fat jar? I must be missing something.

**Comment by sbawaska** [comment]
There are a couple of reasons:
1. This is an extra step that the user will have to perform
2. On both maven and gradle, this results in producing two jar files, one with all dependencies and one without. Our buildpack does not like two jars and results in a build failure: https://github.com/projectriff/riff-buildpack/issues/35. People will have to workaround this limitation by ensuring that the build produces only one jar, which is not straight forward: https://github.com/projectriff/riff-buildpack/issues/35#issuecomment-446348863

**Comment by dsyer** [comment]
I don’t buy that yet. Fat jars are completely normal. It’s the default from start.spring.io for example. Why would you need 2 jars? And if that’s necessary and it’s a problem then I think that’s an issue for the buildpack, isn’t it?

**Comment by ericbottard** [comment]
Closing this, as the build(pack) correctly does the correct thing when using the boot plugin.
