### ISSUE TITLE
Explicit deactivation of functional registration doesn't work

### ISSUE THREAD

**Issue by fbiville** [projectriff/java-function-invoker#122]
The current implementation of `JavaFunctionInvokerApplication` correlates the presence of `--spring.functional.enabled` with the functional registration activation regardless of the value passed to that option.

In other words, passing `--spring.functional.enabled=false` has currently the same effect as `--spring.functional.enabled`.

**Comment by dsyer** [comment]
I don't think that's true precisely (the invoker just passes the args it was called with down to the user function, and the user function can be functional or non-functional, depending on the value of that flag). Do you have a test that shows what you mean?

**Comment by fbiville** [comment]
Here is a debugging session that shows how `--spring.functional.enabled=false` passed to main still enables functional registration.
<img width="908" alt="screenshot 2019-02-05 at 11 20 12" src="https://user-images.githubusercontent.com/445792/52266990-22302a00-2938-11e9-9466-ac5e2fec266d.png">

**Comment by dsyer** [comment]
Yes, but when that boolean is true, nothing happens. It's a bit confusing, I admit, but it's not actually changing the behaviour is it?
