### ISSUE TITLE
Functions using POJO payloads with @JsonProperty not working as expected

### ISSUE THREAD

**Issue by trisberg** [projectriff/java-function-invoker#136]
It seems that due to the way functions are loaded there is a classloading issue where the jackson annotations aren't detected when POJOs are deserialized.

Sample function: https://github.com/trisberg/pojo-fun

This function uses a POJO that has this on the `last` property:

```
    @JsonProperty("LastName")
    public String getLast() {
        return last;
    }
```

Building this locally and running with:

```
pack build pojo --builder projectriff/builder:0.4.0-20190815183716-34a63d2fdc243d66
docker run -it -p 8080:8080 pojo
```

gives this when invoking the function:

```
$ curl localhost:8080 -H 'Content-Type: application/json' -d '{"first": "Bob", "LastName": "Smith"}' ; echo
PlatformEvent [first=Bob, last=null]
$ curl localhost:8080 -H 'Content-Type: application/json' -d '{"first": "Bob", "last": "Smith"}' ; echo
PlatformEvent [first=Bob, last=Smith]
```

**Comment by trisberg** [comment]
It looks like the invoker rewrite in #133 fixes this issue. We can hopefully close this issue once that merges.

**Comment by fbiville** [comment]
@trisberg can this issue be closed now that the rewrite is merged?
