### ISSUE TITLE
Investigate regression with latest Spring Cloud Function

### ISSUE THREAD

**Issue by fbiville** [projectriff/java-function-invoker#144]
We recently [updated](https://github.com/projectriff/java-function-invoker/commit/229b4e8b1bf11ea7787c3a0515826a4a39658db6) the invoker to adapt to the last SNAPSHOT changes of [SCF@master](https://github.com/spring-cloud/spring-cloud-function).
However, all the integration tests now fail.

We also cannot point to the last released milestone (v3.0.0.M3 at the time of writing), as it includes [this commit](https://github.com/spring-cloud/spring-cloud-function/commit/11a6e923ee08aaaa123747d9a5f6b2e1dfbd85c9) which removes the function `getFunctionType` that the invoker used to rely on (and with which integration tests were passing).

**Comment by fbiville** [comment]
Note that the linked commit didn't cause a CI failure as the CI was improperly invoking the Maven phase `integration-test` without the subsequent `verify`, hence ignoring integration test results. This is [now fixed](https://github.com/projectriff/java-function-invoker/commit/c9e17fcd7021c6df6ef6bc18d63da2c1a8e28347).

**Comment by ericbottard** [comment]
This has been fixed
