### ISSUE TITLE
Unable to use Flux in function signature

### ISSUE THREAD

**Issue by trisberg** [projectriff/java-function-invoker#159]
I have a boot app with a function with a `Function<Flux<String>, Flux<String>>` signature and it works running from command line and with the older jar invoker build with Kaniko. It doesn't work when building with the buildpack. When invoking the function I get `{"timestamp":"Oct 10, 2018 5:48:04 PM","status":500,"error":"Internal Server Error","message":"java.lang.String cannot be cast to reactor.core.publisher.Flux","path":"/"}`.

Test app:

```
riff function create java cap \
  --git-repo https://github.com/trisberg/capitalize-boot.git \
  --git-revision flux \
  --image gcr.io/cf-spring-funkytown/capitalize-boot \
  --verbose
riff service invoke cap -- -w '\n' -H 'Content-Type: text/plain' -d 'hello there, how are you?'
riff service delete cap
```

**Comment by trisberg** [comment]
Maybe we need to discuss the best approach with @dsyer who suggested not using the jar to improve startup performance.

**Comment by ericbottard** [comment]
This has become irrelevant with the new invoker / Spring Cloud Function.
