### ISSUE TITLE
When scaled down, Fluxes don't complete() nicely.

### ISSUE THREAD

**Issue by ericbottard** [projectriff/java-function-invoker#175]
The the streaming-processor and the invoker are being scaled down for lack of items to process, the app may be "gracefully" shutdown, but the input Flux does not complete(). This is problematic because the function may have accumulated state for which it needs to emit some final outputs.

One way to witness this behaviour is to have a function that uses GroupBy() or similar operators. One would expect the groups to be emitted when the function is scaled down, but this does not happen.

**Comment by scothis** [comment]
At the point the processor is scaling down, it's too late to emit anything reliably. We need to prevent the processor from scaling down while it's performing work. Of course, that requires us to define what "performing work" means and how we detect it.
