### ISSUE TITLE
POJO used as function argument requires no-arg constructor

### ISSUE THREAD

**Issue by trisberg** [projectriff/java-function-invoker#181]
Deploying a function that takes an immutable POJO with the core deployer and can't seem to invoke it since the POJO doesn't have a no-arg constructor.

Using this POJO:

```
package com.springdeveloper.demo;

public class Greeting {

	private String type;
	private String name;

	public Greeting(String type, String name) {
		this.type = type;
		this.name = name;
	}

	public String getType() {
		return type;
	}

	public String getName() {
		return name;
	}
}
```

I get this error invoking it:

```
$ curl ${ingress} -H 'Host: hello.default.example.com' -H 'Content-Type: application/json' -H 'Accept: text/plain' -d '{"type": "test", "name": "riff"}' && echo
rpc error: code = Unknown desc = Could not read JSON: Cannot construct instance of `com.springdeveloper.demo.Greeting` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"type": "test", "name": "riff"}"; line: 1, column: 2]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.springdeveloper.demo.Greeting` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"type": "test", "name": "riff"}"; line: 1, column: 2]
```

If I run the function locally it works fine:

```
$ curl localhost:8080 -H 'Content-Type: application/json' -H 'Accept: text/plain' -d '{"type": "test", "name": "riff"}' && echo
hello riff [test]
```
If I add no-arg constructor it also works fine using the core deployer.

Code and instruction in the README.md - https://github.com/trisberg/riff-java-samples/tree/master/hello-boot-fun-web-pojo

**Comment by ericbottard** [comment]
This is (if I'm not mistaken) because when you "run locally" you're using spring-cloud-function-web whose old serialization mechanism (which only mainly focuses on JSON) is different from the new SCF pluggable mechanism. When things converge back again, the discrepancy should disappear, in one direction or the other (requiring a no-arg constructor doesn't strike me as shocking)

**Comment by ericbottard** [comment]
cc @olegz
