### ISSUE TITLE
Support for running the invoker on JDK11

### ISSUE THREAD

**Issue by jldec** [projectriff/java-function-invoker#20]
Not sure where in the priority list this will land, but capturing here for planning purposes.

@dsyer wrote
> JDK9 doesn't have tools.jar
> So quite possibly there are bits of riff that don't work
> JDK9 also doesn't use `URLClassLoader` by default. The `java-function-invoker` probably still depends on that.

**Comment by dsyer** [comment]
I think it works fine now, and Java 10 is almost as fast as Java 8 (9 was slower on startup).

**Comment by trisberg** [comment]
Tests fail for me with Java 9 and `.mvnw package` fails with Java 10.

**Comment by dsyer** [comment]
Java 9 is dead, so I'd say that's irrelevant. No-one said that Maven had to work with Java 10, so I don't know why that is relevant either. The app runs with Java 10 out of the box. I don't really even see a need to test that on an ongoing basis, if the base image we prepare is Java 8 anyway.

**Comment by trisberg** [comment]
So maybe we should rename this issue to "Support for running functions built with JDK 9 or 10", but that still only works if we built the classes for JDK 8. So not sure what "Support for JDK9" actually means here.

**Comment by trisberg** [comment]
Changed to support JDK 11 since that is out now

**Comment by dsyer** [comment]
See also https://github.com/spring-cloud/spring-cloud-function/issues/251

**Comment by dsyer** [comment]
The latest versions are already running on JDK11
