### ISSUE TITLE
document usage info in README

### ISSUE THREAD

**Issue by jldec** [projectriff/java-function-invoker#43]
Could we convert the README for this repo to markdown, and add some basic usage info to describe how functions are loaded at runtime, and the API for invocations?

This would allow us to generate "how to write functions" for each language in the docs at projectriff.io.

see https://github.com/projectriff/projectriff.io/issues/6

**Comment by ericbottard** [comment]
Why convert this to md? All our other repos are using asciidoc (which again, is way more powerful and legible IMHO). If we ever want to turn our READMEs (and other docs) into some consolidated documentation, we'll be better off with asciidoc.

**Comment by jldec** [comment]
The existing consolidated docs in the projectriff.io repo use markdown.

**Comment by dsyer** [comment]
+1 to asciidoctor. We'll have to write our own tooling to merge together docs written in markdown, while asciidoctor stands and laughs at us.

**Comment by scothis** [comment]
I'd like to add the `riff init java` and `riff create java` command docs based on the java-invoker.yaml.

Right now the docs command can generate markdown, but not asciidoc. Although the asciidoc include is also compelling. It's worth playing with the intersection of the two to figure out which is "best".

**Comment by dsyer** [comment]
See also #46 (possible duplicate)
