### ISSUE TITLE
Simple apps should not require 'spring-cloud-function` dependency

### ISSUE THREAD

**Issue by dturanski** [projectriff/java-function-invoker#45]
e.g.,  this fails without it https://github.com/dturanski/twitter-source-function/tree/boot-1.5

**Comment by dsyer** [comment]
Not sure what you mean by this. Simple apps do not require Spring at all. Which part of the app you linked to do you think ought to work without Spring Cloud Function?

**Comment by dturanski** [comment]
This issue is something you observed and suggested as an issue while we were looking at my sample. My take is if a spring app has a bean that implements a function, the JFI already brings SCF so the function shouldn’t need  the dependency unless it is required to run standalone as well.

**Comment by dsyer** [comment]
I don't think that is correct, unless you are running with a single class loader. As soon as you require the invoker to run a jar in its own class loader, it has to bring all the classes with it (except shared classes from reactor-core).

**Comment by dturanski** [comment]
Good enough

**Comment by dsyer** [comment]
The issue currently is that there is no way to inspect the functions on the other side of the class loader divide to find out their input and output types. Dropping spring-cloud-function-context in there is a good solution (and a cheap one), but I guess I can see that not everyone wants to have to do that. We might like to support this at some point, but maybe not a high priority right now.

**Comment by ericbottard** [comment]
The classloading model has changed and this becomes irrelevant, SCF is no longer needed in the function artifact
