### ISSUE TITLE
Kotlin/JVM support

### ISSUE THREAD

**Issue by sdeleuze** [projectriff/java-function-invoker#81]
Kotlin support should be low hanging fruit for this project, and a good fit given its first class function support. I can probably help to make the 2 last use cases working, but could you help me to understand why the first one is not working? 

## Function<String, String>

I have tried to use `java-function-invoker` with a Kotlin port of the `greeter` example, but I was not able to make it work even with this conservative version that is using `java.util.function.Function`.

```
class Greeter : Function<String, String> {
	override fun apply(name: String) = "Hello $name"
}
```
This code generates the following bytecode.

```
public final class functions/Greeter implements java/util/function/Function  {

  // access flags 0x1
  public apply(Ljava/lang/String;)Ljava/lang/String;
  @Lorg/jetbrains/annotations/NotNull;() // invisible
  @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
   L0
    ALOAD 1
    LDC "name"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkParameterIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
   L1
    LINENUMBER 6 L1
    NEW java/lang/StringBuilder
    DUP
    INVOKESPECIAL java/lang/StringBuilder.<init> ()V
    LDC "Hello "
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    ALOAD 1
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    INVOKEVIRTUAL java/lang/StringBuilder.toString ()Ljava/lang/String;
    ARETURN
   L2
    LOCALVARIABLE this Lfunctions/Greeter; L0 L2 0
    LOCALVARIABLE name Ljava/lang/String; L0 L2 1
    MAXSTACK = 2
    MAXLOCALS = 2

  // access flags 0x1041
  public synthetic bridge apply(Ljava/lang/Object;)Ljava/lang/Object;
   L0
    LINENUMBER 5 L0
    ALOAD 0
    ALOAD 1
    CHECKCAST java/lang/String
    INVOKEVIRTUAL functions/Greeter.apply (Ljava/lang/String;)Ljava/lang/String;
    ARETURN
    MAXSTACK = 2
    MAXLOCALS = 2

  // access flags 0x1
  public <init>()V
   L0
    LINENUMBER 5 L0
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    RETURN
   L1
    LOCALVARIABLE this Lfunctions/Greeter; L0 L1 0
    MAXSTACK = 1
    MAXLOCALS = 1

  @Lkotlin/Metadata;(mv={1, 1, 10}, bv={1, 0, 2}, k=1, d1={"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\u000e\n\u0002\u0008\u0004\u0018\u00002\u000e\u0012\u0004\u0012\u00020\u0002\u0012\u0004\u0012\u00020\u00020\u0001B\u0005\u00a2\u0006\u0002\u0010\u0003J\u0010\u0010\u0004\u001a\u00020\u00022\u0006\u0010\u0005\u001a\u00020\u0002H\u0016\u00a8\u0006\u0006"}, d2={"Lfunctions/Greeter;", "Ljava/util/function/Function;", "", "()V", "apply", "name", "production sources for module greeter"})
}
```
I tend to think this should work even without any kind of specific Kotlin reflection support.

## Function types 

It would be nice to support Kotlin function types which are more idiomatic. This could require usage of Kotlin reflection.

```
class Greeter : (String) -> String {
	override fun invoke(name: String) = "Hello $name"
}
```

## Top level functions

Since Kotlin supports pure functions not wrapped in classes, this is the most idiomatic form to support via a `functions.greeter` handler support implemented leveraging Kotlin reflection.

```
fun greeter(name: String) = "Hello $name"
```

**Comment by trisberg** [comment]
I'll give it a try. Any Kotlin tips? I'll try installing it now and build that function.

**Comment by sdeleuze** [comment]
Thanks!

I can share my test project if that can help.

`src/main/kotlin/Greeter.kt`
```
package functions

import java.util.function.Function

class Greeter : Function<String, String> {

	override fun apply(name: String) = "Hello $name"
}
```

`pom.xml`
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>io.projectriff.samples</groupId>
	<artifactId>greeter</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>

	<name>greeter</name>
	<description>Sample project for riff using String</description>
	<url>https://github.com/projectriff/java-function-invoker</url>

	<properties>
    	<kotlin.version>1.2.41</kotlin.version>
	</properties>

	<dependencies>
	    <dependency>
	        <groupId>org.jetbrains.kotlin</groupId>
	        <artifactId>kotlin-stdlib</artifactId>
	        <version>${kotlin.version}</version>
	    </dependency>
	</dependencies>

	<build>
	    <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
	
	    <plugins>
	        <plugin>
	            <artifactId>kotlin-maven-plugin</artifactId>
	            <groupId>org.jetbrains.kotlin</groupId>
	            <version>${kotlin.version}</version>

	            <configuration>
			<jvmTarget>1.8</jvmTarget>
                    </configuration>
				<executions>
	                <execution>
	                    <id>compile</id>
	                    <goals> <goal>compile</goal> </goals>
	                </execution>
	            </executions>
	        </plugin>
	    </plugins>
	</build>

</project>
```

**Comment by trisberg** [comment]
Can I compile the class without maven just using kotlinc?

**Comment by sdeleuze** [comment]
Not sure, I have never tried (you need the stdlib dependency).

**Comment by trisberg** [comment]
Looks like we are missing some kotlin jars

```
default/kotlin-greeter-5d867d8b47-msw66[main]: Exception in thread "grpc-default-executor-0" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
default/kotlin-greeter-5d867d8b47-msw66[main]: 	at functions.Greeter.apply(Greeter.kt)
default/kotlin-greeter-5d867d8b47-msw66[main]: 	at functions.Greeter.apply(Greeter.kt:5)
default/kotlin-greeter-5d867d8b47-msw66[main]: 	at org.springframework.cloud.function.core.IsolatedFunction.apply(IsolatedFunction.java:47)
default/kotlin-greeter-5d867d8b47-msw66[main]: 	at org.springframework.cloud.function.core.FluxFunction.lambda$apply$0(FluxFunction.java:47)
...
```

**Comment by trisberg** [comment]
So after adding the contents of `org.jetbrains.kotlin:kotlin-runtime:1.2.41` to the `src/main/resources/` directory and rebuilding I was able to create a function and run it:

```
$ riff publish -i greeter -d Kotlin -r
Posting to http://35.231.168.181:80/requests/greeter
Hello Kotlin
```

**Comment by trisberg** [comment]
Here is a link to a working example: https://github.com/trisberg/kotlin-greeter

**Comment by sdeleuze** [comment]
Thanks, I understand now.

Using that as a starting point, I would like to work on a PR that would use Kotlin reflection to support function types and top level functions. Should I follow the same kind of principle we follow in Spring Framework, I mean classpath detection + Kotlin specific features wrapped into a dedicated inner class to enable optionally such support only if Kotlin is on the classpath?

Any guidance appreciated.

**Comment by trisberg** [comment]
I would think that it would be best to create a kotlin-function-invoker that extends the Java invoker plus adds `kotlin-runtime` and maybe `kotlin-stdlib` dependencies so the function author doesn't have to worry about that. You could then do some additional detection and wrapping of the function code - @dsyer would be the best source for advice since he wrote the Java invoker.

**Comment by sdeleuze** [comment]
I like the idea, that could allow me to add support for Kotlin/Native and scripting later. Any thoughts @dsyer?

**Comment by dsyer** [comment]
I don't have any strong opinions. Probably a separate invoker makes sense, but can imagine not doing it that way as well, as long as it doesn't bloat the image or slow down the app when it starts. The java-function-invoker can already be used as a library. Just do this:

```
@Import(GrpcConfiguration.class)
@EnableConfigurationProperties(FunctionProperties.class)
```

on a Spring `@Configuration` class.

**Comment by sdeleuze** [comment]
Thanks for your feedback, I will contribute a dedicated `kotlin-function-invoker` project and use https://github.com/projectriff/riff/issues/283 for tracking this feature.
